# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/lilya/Documents/ds3_task/task_dsp/constraints/Artix-7-XC735T.xdc

# Block Designs: bd/design_dsp/design_dsp.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dsp || ORIG_REF_NAME==design_dsp} -quiet] -quiet

# IP: bd/design_dsp/ip/design_dsp_alu_top_wrapper_0_0/design_dsp_alu_top_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dsp_alu_top_wrapper_0_0 || ORIG_REF_NAME==design_dsp_alu_top_wrapper_0_0} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: bd/design_dsp/ip/design_dsp_dsp_macro_0_1/design_dsp_dsp_macro_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_dsp_dsp_macro_0_1 || ORIG_REF_NAME==design_dsp_dsp_macro_0_1} -quiet] -quiet

# XDC: c:/Users/lilya/Documents/ds3_task/task_dsp/project/task_DSP.gen/sources_1/bd/design_dsp/design_dsp_ooc.xdc
