# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lilya/Documents/ds3_task/task_5/project/task_5_ULTRA_PROCESSOR.srcs/sources_1/bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_axi_gpio_0_1/Super_Ultra_Processor_axi_gpio_0_1.xci
# IP: The module: 'Super_Ultra_Processor_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lilya/Documents/ds3_task/task_5/project/task_5_ULTRA_PROCESSOR.gen/sources_1/bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_axi_gpio_0_1/Super_Ultra_Processor_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Super_Ultra_Processor_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lilya/Documents/ds3_task/task_5/project/task_5_ULTRA_PROCESSOR.gen/sources_1/bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_axi_gpio_0_1/Super_Ultra_Processor_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Super_Ultra_Processor_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/lilya/Documents/ds3_task/task_5/project/task_5_ULTRA_PROCESSOR.srcs/sources_1/bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_axi_gpio_0_1/Super_Ultra_Processor_axi_gpio_0_1.xci
# IP: The module: 'Super_Ultra_Processor_axi_gpio_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lilya/Documents/ds3_task/task_5/project/task_5_ULTRA_PROCESSOR.gen/sources_1/bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_axi_gpio_0_1/Super_Ultra_Processor_axi_gpio_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Super_Ultra_Processor_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/lilya/Documents/ds3_task/task_5/project/task_5_ULTRA_PROCESSOR.gen/sources_1/bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_axi_gpio_0_1/Super_Ultra_Processor_axi_gpio_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Super_Ultra_Processor_axi_gpio_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
