# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lilya/Documents/ds3_task/task_dsp/project/task_DSP.srcs/sources_1/bd/design_dsp/ip/design_dsp_dsp_macro_0_1/design_dsp_dsp_macro_0_1.xci
# IP: The module: 'design_dsp_dsp_macro_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lilya/Documents/ds3_task/task_dsp/project/task_DSP.gen/sources_1/bd/design_dsp/ip/design_dsp_dsp_macro_0_1/design_dsp_dsp_macro_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dsp_dsp_macro_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/lilya/Documents/ds3_task/task_dsp/project/task_DSP.srcs/sources_1/bd/design_dsp/ip/design_dsp_dsp_macro_0_1/design_dsp_dsp_macro_0_1.xci
# IP: The module: 'design_dsp_dsp_macro_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lilya/Documents/ds3_task/task_dsp/project/task_DSP.gen/sources_1/bd/design_dsp/ip/design_dsp_dsp_macro_0_1/design_dsp_dsp_macro_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_dsp_dsp_macro_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
