# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lilya/Documents/ds3_task/task_dsp/project/task_DSP.srcs/sources_1/bd/design_dsp/ip/design_dsp_alu_top_wrapper_0_0/design_dsp_alu_top_wrapper_0_0.xci
# IP: The module: 'design_dsp_alu_top_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/lilya/Documents/ds3_task/task_dsp/project/task_DSP.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: c:/Users/lilya/Documents/ds3_task/task_dsp/project/task_DSP.srcs/sources_1/bd/design_dsp/ip/design_dsp_alu_top_wrapper_0_0/design_dsp_alu_top_wrapper_0_0.xci
# IP: The module: 'design_dsp_alu_top_wrapper_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Users/lilya/Documents/ds3_task/task_dsp/project/task_DSP.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet
