# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/lilya/Documents/ds3_task/task_5/constraints/Artix-7-XC735T.xdc

# Block Designs: bd/Super_Ultra_Processor/Super_Ultra_Processor.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Super_Ultra_Processor || ORIG_REF_NAME==Super_Ultra_Processor} -quiet] -quiet

# IP: bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_alu_top_wrapper_0_0/Super_Ultra_Processor_alu_top_wrapper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Super_Ultra_Processor_alu_top_wrapper_0_0 || ORIG_REF_NAME==Super_Ultra_Processor_alu_top_wrapper_0_0} -quiet] -quiet

# IP: bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_axi_gpio_0_0/Super_Ultra_Processor_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Super_Ultra_Processor_axi_gpio_0_0 || ORIG_REF_NAME==Super_Ultra_Processor_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_axi_gpio_0_1/Super_Ultra_Processor_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Super_Ultra_Processor_axi_gpio_0_1 || ORIG_REF_NAME==Super_Ultra_Processor_axi_gpio_0_1} -quiet] -quiet

# IP: bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_microblaze_0_0/Super_Ultra_Processor_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Super_Ultra_Processor_microblaze_0_0 || ORIG_REF_NAME==Super_Ultra_Processor_microblaze_0_0} -quiet] -quiet

# IP: bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_dlmb_v10_0/Super_Ultra_Processor_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Super_Ultra_Processor_dlmb_v10_0 || ORIG_REF_NAME==Super_Ultra_Processor_dlmb_v10_0} -quiet] -quiet

# IP: bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_ilmb_v10_0/Super_Ultra_Processor_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Super_Ultra_Processor_ilmb_v10_0 || ORIG_REF_NAME==Super_Ultra_Processor_ilmb_v10_0} -quiet] -quiet

# IP: bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_dlmb_bram_if_cntlr_0/Super_Ultra_Processor_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Super_Ultra_Processor_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==Super_Ultra_Processor_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_ilmb_bram_if_cntlr_0/Super_Ultra_Processor_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Super_Ultra_Processor_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==Super_Ultra_Processor_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_lmb_bram_0/Super_Ultra_Processor_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Super_Ultra_Processor_lmb_bram_0 || ORIG_REF_NAME==Super_Ultra_Processor_lmb_bram_0} -quiet] -quiet

# IP: bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_microblaze_0_axi_periph_imp_xbar_0/Super_Ultra_Processor_microblaze_0_axi_periph_imp_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Super_Ultra_Processor_microblaze_0_axi_periph_imp_xbar_0 || ORIG_REF_NAME==Super_Ultra_Processor_microblaze_0_axi_periph_imp_xbar_0} -quiet] -quiet

# IP: bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_microblaze_0_axi_periph_0/Super_Ultra_Processor_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Super_Ultra_Processor_microblaze_0_axi_periph_0 || ORIG_REF_NAME==Super_Ultra_Processor_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_mdm_1_0/Super_Ultra_Processor_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Super_Ultra_Processor_mdm_1_0 || ORIG_REF_NAME==Super_Ultra_Processor_mdm_1_0} -quiet] -quiet

# IP: bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_clk_wiz_1_0/Super_Ultra_Processor_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Super_Ultra_Processor_clk_wiz_1_0 || ORIG_REF_NAME==Super_Ultra_Processor_clk_wiz_1_0} -quiet] -quiet

# IP: bd/Super_Ultra_Processor/ip/Super_Ultra_Processor_rst_clk_wiz_1_100M_0/Super_Ultra_Processor_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Super_Ultra_Processor_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==Super_Ultra_Processor_rst_clk_wiz_1_100M_0} -quiet] -quiet

# XDC: c:/Users/lilya/Documents/ds3_task/task_5/project/task_5_ULTRA_PROCESSOR.gen/sources_1/bd/Super_Ultra_Processor/Super_Ultra_Processor_ooc.xdc
